import { NewsCategory } from "@/types/news";

export const CATEGORY_KEYWORDS: Record<
  Exclude<NewsCategory, "All">,
  string[]
> = {
  Local: [
    "fiji",
    "suva",
    "nadi",
    "lautoka",
    "labasa",
    "local",
    "community",
    "pacific",
    "fijian",
    "province",
    "vanua",
    "village",
  ],
  Politics: [
    "politics",
    "parliament",
    "election",
    "minister",
    "government",
    "policy",
    "cabinet",
    "opposition",
    "mp",
    "bill",
    "law",
    "legislation",
  ],
  Technology: [
    "technology",
    "digital",
    "internet",
    "cyber",
    "tech",
    "online",
    "software",
    "computer",
    "innovation",
    "artificial intelligence",
    "ai",
    "mobile",
    "telecommunications",
  ],
  Business: [
    "business",
    "economy",
    "market",
    "trade",
    "finance",
    "company",
    "investment",
    "industry",
    "corporate",
    "tourism",
    "export",
    "dollar",
    "bank",
    "real estate",
  ],
  Health: [
    "health",
    "medical",
    "hospital",
    "disease",
    "healthcare",
    "covid",
    "wellness",
    "clinic",
    "doctor",
    "patient",
    "vaccination",
    "medicine",
    "treatment",
  ],
  World: [
    "world",
    "international",
    "global",
    "foreign",
    "overseas",
    "diplomatic",
    "un",
    "united nations",
    "asia",
    "pacific",
    "australia",
    "new zealand",
  ],
  Sports: [
    "sports",
    "rugby",
    "football",
    "cricket",
    "athletics",
    "game",
    "tournament",
    "match",
    "player",
    "team",
    "olympics",
    "soccer",
    "netball",
    "boxing",
    "championship",
  ],
};
